### ISSUE TITLE
client.py - scan() routine may cause reads that are not on point boundaries

### ISSUE THREAD

**Issue by bobfox** [sunspec/pysunspec2#16]
The scan() routine in modbus/client.py performs the scan incorrectly. While performing the scan, it reads the full contents of each model rather than just the model id and length. For models that are larger than the maximum Modbus read request (125 registers), this may cause a read to occur starting in the middle of a point due to the read request having to be broken into multiple Modbus requests. It is guaranteed this will happen with the current model 701 definition if maximum sized reads are performed.

SunSpec Modbus server implementations may reject read requests that are not on point boundaries causing the scan to fail. SunSpec Modbus clients must only perform reads on point boundaries.

The scan routine should be updated to only access the model id and length during the scan. After the scan, the model definition can then be used to perform reads on point boundaries.

**Comment by shelcrow** [comment]
Fixed in commit f2f61303ba1c8ab4d20ec898d7ae14272c3ea1b1.
