### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by altendky** [sunspec/pysunspec2#20]
What is the license for this project?  Whatever it is, it ought to be added as a license file and also listed in the `setup.py` file under both the classifiers and the license parameter.  If specified in each file as well then that ought to be consistent.  `spreadsheet.py` for example seems to have an MIT license and `device.py` has nothing.

**Comment by bobfox** [comment]
We have moved to the apache license. We will clean it up.

**Comment by shelcrow** [comment]
Fixed in commit 99470552dc8681ee234422d1470e70370d42a872.
