### ISSUE TITLE
Add support for model 1 with a length of 67 to support legacy implementations

### ISSUE THREAD

**Issue by bobfox** [sunspec/pysunspec2#30]
Originally, model 1 did not have a pad register at the end so the length is 67. The library should support model 1 with a length of 67 even though it does not conform to the model definition length of 68. This is the one and only condition of this type and allows support for legacy devices.

**Comment by bobfox** [comment]
The length in the 'L' point is actually 65 for a total length of 67.

**Comment by shelcrow** [comment]
Fixed in commit 4405d92786733f1fed118be9c468eaaf97ca8b1d.
