### ISSUE TITLE
smdx.from_smdx() does not put `size` attribute in points

### ISSUE THREAD

**Issue by jmmgenerac** [sunspec/pysunspec2#34]
https://github.com/sunspec/pysunspec2/blob/4405d92786733f1fed118be9c468eaaf97ca8b1d/sunspec2/smdx.py#L159

When using `smdx.from_smdx()` to convert from smdx files to dictionary, the `size` attribute is not created.

As a workaround, I found that using `smdx.from_smdx()` -> `spreadsheet.to_spreadsheet()` -> `spreadsheet.from_spreadsheet()` seems to do the job.

However, it would be great if `smdx.from_smdx()` performed the proper conversion on its own.

**Comment by bobfox** [comment]
We will add this in the update coming out this week.
