### ISSUE TITLE
suns.py tool

### ISSUE THREAD

**Issue by alexdelprete** [sunspec/pysunspec2#40]
With pysunspec there was a nice CLI utility, suns.py. With pysunspec2 I didn't find it.

Can I adapt the suns.py making it work with pysunspec2?

Thanks a lot for this library.

**Comment by bobfox** [comment]
We will look at adding it in pysunspec2 in the next release.

**Comment by alexdelprete** [comment]
> We will look at adding it in pysunspec2 in the next release.

Thanks a lot Bob.
