### ISSUE TITLE
Support python 3.7 to 3.11

### ISSUE THREAD

**Issue by sv3ndk** [sunspec/pysunspec2#81]
PySunspec readme mentions python 3.5 to 3.8 are supported.

We've been using it at my company in production with python 3.9 for a couple of months now and it seems to work fine. Our usage is limited to interraction with one inverter over TCP.

I created a quick [tox configuration](https://github.com/sv3ndk/pysunspec2/blob/tox_init/tox.ini#L4) for it and the unit tests are green when executed against python 3.7, 3.8, 3.9, 3.10 or 3.11.

Also, python 3.5 and 3.6 have been marked as end-of-life for a few years now, so maybe they should be removed from the list of supported python versions?

If you're interrested, I'm happy to send a quick PR with this tox config and a readme update telling how to use it.

**Comment by Kudrat9** [comment]
Hi,

Thanks for letting us know. And for the testing you've done.

Sure, you can create a PR and once our internal team approves it, we'll merge it and update the readme.

Thanks.
